=== Prashant111222/Music-Store/Development/catalog_19033562.dtd
<!ELEMENT store (detail,albums)>
<!ELEMENT detail (name,address,phoneNo+,faxNo*,logo)>
<!ATTLIST detail url CDATA #REQUIRED>
<!ATTLIST detail registrationNo ID #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT address (country,city,street,zip?)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT phoneNo (#PCDATA)>
<!ELEMENT faxNo (#PCDATA)>
<!ELEMENT logo EMPTY>
<!ELEMENT albums (album+)>

<!ELEMENT album (title,artist,songs,releasedYear,producers,format,value,description)>
<!ATTLIST album albumID ID #REQUIRED>
<!ATTLIST album label CDATA #REQUIRED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT songs (song+)>

<!ELEMENT song (title,singers,writers,directors?)>
<!ATTLIST song isrc ID #REQUIRED>
<!ATTLIST song length CDATA #REQUIRED>
<!ATTLIST song genre CDATA #REQUIRED>

<!ELEMENT singers (singer+)>
<!ATTLIST singers singerType (solo|duet|band|chrous) "solo">

<!ELEMENT singer (firstName,lastName)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>

<!ELEMENT writers (writer+)>
<!ELEMENT writer (firstName,lastName)>

<!ELEMENT directors (director+)>
<!ELEMENT director (firstName,lastName)>

<!ELEMENT releasedYear (#PCDATA)>
<!ELEMENT producers (producer+)>
<!ELEMENT producer (title?,firstName,lastName)>
<!ATTLIST producer producerType (individual|band|organization) #IMPLIED>

<!ELEMENT format (#PCDATA)>
<!ELEMENT value (price,discount?)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency CDATA #FIXED "$">

<!ELEMENT discount (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== Prashant111222/Music-Store/Development/catalog_19033562.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE store SYSTEM "./catalog_19033562.dtd"> -->
<?xml-stylesheet type="text/css" href="catalog_19033562.css"?>

<store
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="./catalog_19033562.xsd"
>
    <detail url="www.musicorchestra.com" registrationNo="PAN-213-342-887">
        <name>Music Orchestra</name>
        <address>
            <country>Nepal</country>
            <city>Kathmandu</city>
            <street>Durbar Marga</street>
        </address>
        <phoneNo>9824332116</phoneNo>
        <phoneNo>9862338229</phoneNo>
        <faxNo>+97715216505</faxNo>
        <logo/>
    </detail>
    
    <albums>
        <album albumID="ALB-2100-1789-101" label="Republic, XO">
            <title>After Hours</title>
            <artist>The Weeknd</artist>
            <songs>
                <song isrc="US-UG1-20-00650" length="4:52" genre="R&amp;B Soul">
                    <title>Alone Again</title>
                    <singers singerType="solo">
                        <singer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </singer>
                    </singers>
                    <writers>
                        <writer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </writer>
                        <writer>
                            <firstName>Jason</firstName>
                            <lastName>Quenneville</lastName>
                        </writer>
                        <writer>
                            <firstName>Carlo</firstName>
                            <lastName>Montagnese</lastName>
                        </writer>
                    </writers>
                </song>

                <song isrc="US-UMV-19-02062" length="3:21" genre="Trap">
                    <title>Heartless</title>
                    <singers singerType="solo">
                        <singer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </singer>
                    </singers>
                    <writers>
                        <writer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </writer>
                        <writer>
                            <firstName>Wayne</firstName>
                            <lastName>Montagnese</lastName>
                        </writer>
                        <writer>
                            <firstName>Andre</firstName>
                            <lastName>Proctor</lastName>
                        </writer>
                    </writers>
                    <directors>
                        <director>
                            <firstName>Anton</firstName>
                            <lastName>Tammi</lastName>
                        </director>
                    </directors>
                </song>

                <song isrc="US-UMV-19-02060" length="3:21" genre="Synthwave">
                    <title>Blinding Lights</title>
                    <singers singerType="solo">
                        <singer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </singer>
                    </singers>
                    <writers>
                        <writer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </writer>
                        <writer>
                            <firstName>Max</firstName>
                            <lastName>Martin</lastName>
                        </writer>
                        <writer>
                            <firstName>Oscar</firstName>
                            <lastName>Holter</lastName>
                        </writer>
                    </writers>
                    <directors>
                        <director>
                            <firstName>Anton</firstName>
                            <lastName>Tammi</lastName>
                        </director>
                    </directors>
                </song>

                <song isrc="US-UG1-20-00658" length="3:35" genre="R&amp;B Soul">
                    <title>Save Your Tears</title>
                    <singers singerType="solo">
                        <singer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </singer>
                    </singers>
                    <writers>
                        <writer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </writer>
                        <writer>
                            <firstName>Ahmad</firstName>
                            <lastName>Blashe</lastName>
                        </writer>
                        <writer>
                            <firstName>Oscar</firstName>
                            <lastName>Holter</lastName>
                        </writer>
                    </writers>
                    <directors>
                        <director>
                            <firstName>R.J.</firstName>
                            <lastName>Sanchez</lastName>
                        </director>
                    </directors>
                </song>

                <song isrc="US-UG1-20-00586" length="6:01" genre="Electro House">
                    <title>After Hours</title>
                    <singers singerType="solo">
                        <singer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </singer>
                    </singers>
                    <writers>
                        <writer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </writer>
                        <writer>
                            <firstName>Ahmad</firstName>
                            <lastName>Blashe</lastName>
                        </writer>
                        <writer>
                            <firstName>Mario</firstName>
                            <lastName>Winans</lastName>
                        </writer>
                    </writers>
                    <directors>
                        <director>
                            <firstName>Anton</firstName>
                            <lastName>Tammi</lastName>
                        </director>
                    </directors>
                </song>

                <song isrc="US-UMV-20-00585" length="3:35" genre="R&amp;B Soul">
                    <title>In Your Eyes</title>
                    <singers singerType="solo">
                        <singer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </singer>
                    </singers>
                    <writers>
                        <writer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </writer>
                        <writer>
                            <firstName>Ahmad</firstName>
                            <lastName>Blashe</lastName>
                        </writer>
                        <writer>
                            <firstName>Max</firstName>
                            <lastName>Martin</lastName>
                        </writer>
                    </writers>
                    <directors>
                        <director>
                            <firstName>Anton</firstName>
                            <lastName>Tammi</lastName>
                        </director>
                    </directors>
                </song>

                <song isrc="US-UG1-20-00660" length="3:12" genre="R&amp;B Soul">
                    <title>Until I Bleed Out</title>
                    <singers singerType="solo">
                        <singer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </singer>
                    </singers>
                    <writers>
                        <writer>
                            <firstName>Abel</firstName>
                            <lastName>Tesfaye</lastName>
                        </writer>
                        <writer>
                            <firstName>Wayne</firstName>
                            <lastName>Montagnese</lastName>
                        </writer>
                        <writer>
                            <firstName>Mejdi</firstName>
                            <lastName>Rhars</lastName>
                        </writer>
                    </writers>
                    <directors>
                        <director>
                            <firstName>Anton</firstName>
                            <lastName>Tammi</lastName>
                        </director>
                    </directors>
                </song>
            </songs>
            <releasedYear>2020</releasedYear>
            <producers>
                <producer producerType="individual">
                    <firstName>Jason</firstName>
                    <lastName>Quenneville</lastName>
                </producer>
                <producer producerType="individual">
                    <firstName>Kevin</firstName>
                    <lastName>Parker</lastName>
                </producer>
                <producer producerType="individual">
